name: PR Safe App Manifest & Deploy

on:
  pull_request:
    branches:
      - main

jobs:
  check-safe-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Ensure safe-app.json exists
        run: |
          if [ ! -f safe-app.json ]; then
            echo "safe-app.json missing — creating..."
            cat << 'EOF' > safe-app.json
{
  "name": "Gnosis Vault Assistant",
  "description": "Gnosis Vault Assistant is a secure, non-custodial dashboard for managing Safe (formerly Gnosis Safe) multisig wallets. It offers real-time balances, transaction history, one-click asset transfers, automated signing via Reown AppKit, and cross-chain support for Ethereum, Arbitrum, Polygon, Base, Optimism, and BNB Chain.",
  "shortName": "Vault Assistant",
  "shortDescription": "Manage Safe multisigs with real-time tracking, one-click transfers, and automated signing.",
  "applicationUrl": "https://safe-vault-f44t.vercel.app",
  "iconPath": "/icon.png",
  "developer": {
    "name": "Gnosis Vault Assistant",
    "website": "https://safe-vault-f44t.vercel.app",
    "supportUrl": "https://safe-vault-f44t.vercel.app/support",
    "documentationUrl": "https://safe-vault-f44t.vercel.app/docs",
    "statusUrl": "https://safe-vault-f44t.vercel.app/status",
    "contact": {
      "address": {
        "line1": "2 Woodward Avenue",
        "city": "Detroit",
        "state": "MI",
        "postalCode": "48226",
        "country": "US"
      }
    }
  },
  "networks": [
    { "chainId": "1" },
    { "chainId": "42161" },
    { "chainId": "137" },
    { "chainId": "8453" },
    { "chainId": "10" },
    { "chainId": "56" }
  ],
  "safeAppUrl": "https://safe-vault-f44t.vercel.app/app",
  "verified": true
}
EOF
          fi

      - name: Validate JSON syntax
        run: jq . safe-app.json > /dev/null

      - name: Commit manifest if created or changed
        run: |
          git config --global user.name "safevault-bot"
          git config --global user.email "actions@github.com"
          if [ -n "$(git status --porcelain safe-app.json)" ]; then
            git add safe-app.json
            git commit -m "chore: ensure safe-app.json is present and valid"
            git push origin HEAD:${{ github.head_ref }}
          fi

  deploy-on-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: check-safe-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
