name: Update Changelog on Release

on:
  release:
    types: [published]

permissions:
  contents: write
  pull-requests: write

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get release info
        id: release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update CHANGELOG.md
        run: |
          VERSION="${{ github.event.release.tag_name }}"
          TITLE="${{ github.event.release.name }}"
          BODY="${{ github.event.release.body }}"
          DATE=$(date +'%Y-%m-%d')

          echo "## [${VERSION}] – ${DATE}" > NEW_CHANGELOG.md
          echo "### ${TITLE}" >> NEW_CHANGELOG.md
          echo "" >> NEW_CHANGELOG.md
          echo "${BODY}" >> NEW_CHANGELOG.md
          echo -e "\n---\n" >> NEW_CHANGELOG.md

          cat CHANGELOG.md >> NEW_CHANGELOG.md
          mv NEW_CHANGELOG.md CHANGELOG.md

      - name: Commit and push changelog
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "docs: update changelog for ${{ github.event.release.tag_name }}"
          git push
